from __future__ import annotations

import json
import os
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

from .config import database_url, is_postgres
from .models import Alert, Entry, FeatureSummary

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover, only relevant when postgres deps are missing
    psycopg = None
    dict_row = None


class CursorWrapper:
    def __init__(self, cursor: Any):
        self._cursor = cursor

    @property
    def lastrowid(self) -> Any:
        return getattr(self._cursor, "lastrowid", None)

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    def fetchone(self) -> Any:
        return self._cursor.fetchone()

    def fetchall(self) -> list[Any]:
        return self._cursor.fetchall()


class ConnectionWrapper:
    def __init__(self, connection: Any, postgres: bool):
        self._connection = connection
        self._postgres = postgres

    def execute(self, query: str, params: tuple[Any, ...] | list[Any] | None = None) -> CursorWrapper:
        compiled = query.replace("?", "%s") if self._postgres else query
        cursor = self._connection.execute(compiled, params or ())
        return CursorWrapper(cursor)

    def executescript(self, script: str) -> None:
        for statement in (part.strip() for part in script.split(";")):
            if statement:
                self.execute(statement)


def _resolve_db_path() -> Path:
    root = Path(__file__).resolve().parent.parent
    env_path = os.getenv("DRIFTGAUGE_DB_PATH") or os.getenv("SENTINEL_DB_PATH")
    if env_path:
        return Path(env_path).expanduser()

    default_path = root / "driftgauge.db"
    legacy_path = root / "sentinel.db"
    if legacy_path.exists() and not default_path.exists():
        return legacy_path
    return default_path


DB_PATH = _resolve_db_path()


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


@contextmanager
def get_conn() -> Iterator[ConnectionWrapper]:
    if is_postgres():
        if psycopg is None or dict_row is None:
            raise RuntimeError("Postgres support requires psycopg[binary] to be installed")
        raw_conn = psycopg.connect(database_url(), row_factory=dict_row)
    else:
        db_path = _resolve_db_path()
        db_path.parent.mkdir(parents=True, exist_ok=True)
        raw_conn = sqlite3.connect(db_path)
        raw_conn.row_factory = sqlite3.Row

    wrapped = ConnectionWrapper(raw_conn, postgres=is_postgres())
    try:
        yield wrapped
        raw_conn.commit()
    finally:
        raw_conn.close()


def id_column_sql() -> str:
    if is_postgres():
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def init_db() -> None:
    with get_conn() as conn:
        conn.executescript(
            f"""
            CREATE TABLE IF NOT EXISTS entries (
                id {id_column_sql()},
                user_id TEXT NOT NULL,
                source TEXT NOT NULL,
                text TEXT NOT NULL,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS alerts (
                id {id_column_sql()},
                user_id TEXT NOT NULL,
                risk_score INTEGER NOT NULL,
                level TEXT NOT NULL,
                explanation TEXT NOT NULL,
                recommendations TEXT NOT NULL,
                feature_summary TEXT NOT NULL,
                created_at TEXT NOT NULL
            );
            """
        )


def insert_entry(user_id: str, source: str, text: str, created_at: datetime) -> Entry:
    created_at = created_at.astimezone(timezone.utc)
    with get_conn() as conn:
        if is_postgres():
            row = conn.execute(
                "INSERT INTO entries (user_id, source, text, created_at) VALUES (?, ?, ?, ?) RETURNING id",
                (user_id, source, text, created_at.isoformat()),
            ).fetchone()
            entry_id = row["id"]
        else:
            cur = conn.execute(
                "INSERT INTO entries (user_id, source, text, created_at) VALUES (?, ?, ?, ?)",
                (user_id, source, text, created_at.isoformat()),
            )
            entry_id = cur.lastrowid
    return Entry(id=entry_id, user_id=user_id, source=source, text=text, created_at=created_at)


def list_entries(user_id: str | None = None, limit: int = 50) -> list[Entry]:
    query = "SELECT id, user_id, source, text, created_at FROM entries"
    params: list[object] = []
    if user_id:
        query += " WHERE user_id = ?"
        params.append(user_id)
    query += " ORDER BY created_at DESC LIMIT ?"
    params.append(limit)

    with get_conn() as conn:
        rows = conn.execute(query, params).fetchall()

    return [
        Entry(
            id=row["id"],
            user_id=row["user_id"],
            source=row["source"],
            text=row["text"],
            created_at=datetime.fromisoformat(row["created_at"]),
        )
        for row in rows
    ]


def insert_alert(alert: Alert) -> Alert:
    created_at = alert.created_at or utc_now()
    with get_conn() as conn:
        if is_postgres():
            row = conn.execute(
                """
                INSERT INTO alerts (user_id, risk_score, level, explanation, recommendations, feature_summary, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                (
                    alert.user_id,
                    alert.risk_score,
                    alert.level,
                    alert.explanation,
                    json.dumps(alert.recommendations),
                    alert.feature_summary.model_dump_json(),
                    created_at.isoformat(),
                ),
            ).fetchone()
            alert_id = row["id"]
        else:
            cur = conn.execute(
                """
                INSERT INTO alerts (user_id, risk_score, level, explanation, recommendations, feature_summary, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    alert.user_id,
                    alert.risk_score,
                    alert.level,
                    alert.explanation,
                    json.dumps(alert.recommendations),
                    alert.feature_summary.model_dump_json(),
                    created_at.isoformat(),
                ),
            )
            alert_id = cur.lastrowid
    return alert.model_copy(update={"id": alert_id, "created_at": created_at})


def list_alerts(user_id: str | None = None, limit: int = 50) -> list[Alert]:
    query = "SELECT * FROM alerts"
    params: list[object] = []
    if user_id:
        query += " WHERE user_id = ?"
        params.append(user_id)
    query += " ORDER BY created_at DESC LIMIT ?"
    params.append(limit)

    with get_conn() as conn:
        rows = conn.execute(query, params).fetchall()

    alerts: list[Alert] = []
    for row in rows:
        alerts.append(
            Alert(
                id=row["id"],
                user_id=row["user_id"],
                risk_score=row["risk_score"],
                level=row["level"],
                explanation=row["explanation"],
                recommendations=json.loads(row["recommendations"]),
                created_at=datetime.fromisoformat(row["created_at"]),
                feature_summary=FeatureSummary.model_validate_json(row["feature_summary"]),
            )
        )
    return alerts
